[build]
  publish = "build"
  command = "bun install && bun run build"

[build.environment]
  TZ = "America/Chicago"
  BUN_VERSION = "1.2"

[[headers]]
  for = "/*"
  [headers.values]
    X-Robots-Tag = "noai, noimageai"
