import { file } from "bun";
import { join } from "path";

const PORT = process.env.PORT || 3000;
const PUBLIC_DIR = join(import.meta.dir, "..", "public");

/**
 * Dynamic Bun route handler for /bun
 */
function handleBunRoute(req: Request): Response {
  const url = new URL(req.url);

  // Get current time for dynamic content
  const now = new Date();
  const timestamp = now.toISOString();

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dynamic Bun Page</title>
    <style>
        body {
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
            max-width: 800px;
            margin: 40px auto;
            padding: 20px;
            line-height: 1.6;
        }
        .badge {
            display: inline-block;
            padding: 4px 12px;
            background: #6366f1;
            color: white;
            border-radius: 4px;
            font-size: 14px;
            font-weight: 600;
        }
        .card {
            background: #f8fafc;
            border: 1px solid #e2e8f0;
            border-radius: 8px;
            padding: 20px;
            margin: 20px 0;
        }
        code {
            background: #1e293b;
            color: #f1f5f9;
            padding: 2px 6px;
            border-radius: 4px;
            font-size: 14px;
        }
        h1 { color: #1e293b; }
        h2 { color: #475569; }
        .info { color: #64748b; font-size: 14px; }
        a { color: #6366f1; text-decoration: none; }
        a:hover { text-decoration: underline; }
    </style>
</head>
<body>
    <span class="badge">DYNAMIC</span>
    <h1>🚀 Bun-Powered Dynamic Page</h1>

    <div class="card">
        <h2>This page is served by Bun!</h2>
        <p>Unlike the rest of the site (which is static HTML generated by Hugo),
        this page is dynamically generated by a Bun HTTP server on each request.</p>

        <p class="info">
            <strong>Server Time:</strong> ${timestamp}<br>
            <strong>Request Method:</strong> ${req.method}<br>
            <strong>Request URL:</strong> ${url.pathname}<br>
            <strong>User Agent:</strong> ${req.headers.get("user-agent") || "Unknown"}
        </p>
    </div>

    <div class="card">
        <h2>What's happening here?</h2>
        <ul>
            <li>The Bun server intercepts requests to <code>/bun</code></li>
            <li>Instead of serving static HTML from Hugo, it generates fresh HTML</li>
            <li>Each refresh shows a new timestamp</li>
            <li>All other routes (like <code>/</code>) serve static Hugo content</li>
        </ul>
    </div>

    <div class="card">
        <h2>Next Steps</h2>
        <p>You can extend this to:</p>
        <ul>
            <li>Fetch data from APIs in real-time</li>
            <li>Connect to databases</li>
            <li>Build interactive forms and applications</li>
            <li>Create REST/GraphQL endpoints</li>
            <li>Implement server-side rendering (SSR)</li>
        </ul>
    </div>

    <p><a href="/">← Back to main site</a></p>
</body>
</html>`;

  return new Response(html, {
    headers: {
      "Content-Type": "text/html; charset=utf-8",
      "X-Powered-By": "Bun",
    },
  });
}

/**
 * Serve static files from Hugo's public directory
 */
async function handleStaticFile(pathname: string): Promise<Response> {
  // Handle root path
  let filePath = pathname === "/" ? "/index.html" : pathname;

  // Remove leading slash for join
  if (filePath.startsWith("/")) {
    filePath = filePath.slice(1);
  }

  const fullPath = join(PUBLIC_DIR, filePath);

  try {
    const staticFile = file(fullPath);

    // Check if file exists
    if (await staticFile.exists()) {
      return new Response(staticFile);
    }

    // Try appending index.html for directory paths
    const indexPath = join(fullPath, "index.html");
    const indexFile = file(indexPath);

    if (await indexFile.exists()) {
      return new Response(indexFile);
    }

    // Try appending .html extension
    const htmlPath = `${fullPath}.html`;
    const htmlFile = file(htmlPath);

    if (await htmlFile.exists()) {
      return new Response(htmlFile);
    }

    // 404
    return new Response("404 - Not Found", { status: 404 });
  } catch (error) {
    console.error("Error serving static file:", error);
    return new Response("500 - Internal Server Error", { status: 500 });
  }
}

/**
 * Main request handler
 */
async function handleRequest(req: Request): Promise<Response> {
  const url = new URL(req.url);
  const pathname = url.pathname;

  console.log(`${req.method} ${pathname}`);

  // Handle dynamic /bun route
  if (pathname === "/bun" || pathname === "/bun/") {
    return handleBunRoute(req);
  }

  // Serve static Hugo site for all other routes
  return handleStaticFile(pathname);
}

/**
 * Start the server
 */
const server = Bun.serve({
  port: PORT,
  fetch: handleRequest,
});

console.log(`🚀 Hybrid Hugo + Bun server running on http://localhost:${server.port}`);
console.log(`   - Static site (Hugo): All routes`);
console.log(`   - Dynamic route (Bun): http://localhost:${server.port}/bun`);
console.log(`\nPress Ctrl+C to stop`);
