---
name: lint
on:
  pull_request:
  push:
    branches: [main]

jobs:
  mkdown-lint:
    name: Markdown Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DavidAnson/markdownlint-cli2-action@v19
        with:
          config: .markdownlint.json
          globs: "content/**/*.md"

  svelte-build:
    name: Svelte Components Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: cd components && bun install && bun run build
