---
name: lint
on:
  pull_request:
  push:
    branches: [main]

jobs:
  svelte-build:
    name: SvelteKit Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install && bun run build
